ALTER TABLE investors ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE investors ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE transaction_orders ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE transaction_orders ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE investor_leads ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE investor_leads ADD COLUMN deleted_at TIMESTAMP;
