package com.platizio.wealthtech.domain;
public enum OrderStatus {
    DRAFT, CREATED, PENDING_INVESTOR_ACTION, PAYMENT_PENDING, SUBMITTED, PROCESSING, ACTIVE, PAUSED,
    SUCCESSFUL, FAILED, RETRY_AVAILABLE, COMPLETED, CANCELLED
}
